channels:
  - conda-forge
dependencies:
  - python=3
  - bokeh=0.13
  - dask=0.20
  - jupyterlab=0.35.1
  - numpy
  - pandas
  - pyarrow==0.10.0
  - scikit-learn=0.20
  - matplotlib
  - cartopy
  - nbserverproxy
  - nomkl
  - h5py
  - xarray
